- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
  - name: connect to intranet web server
    uri:
      url: http://servera.lab.example.com
      return_content: yes
      status_code: 200